### ISSUE TITLE
psz length check too high?

### ISSUE THREAD

**Issue by jlopp** [mycroft/generate-genesis#4]
Just a heads up in case you want to look into it.

It seems like the length check for psz is way too high. The tool allows me to attempt generating a block with a psz that is hundreds of characters. If I try that, it simply never finds a block.

Or maybe it isn't specifically the max psz length, but something related to longer pszs. All I know is that when I try generating a genesis block with a psz > 64 chars, I never succeed in minting a block even after having the script run for hours.

**Comment by mycroft** [comment]
Hello, I guess it rings some bell and it might be something I encountered.

Well, it has been a while I've no taken a look into bitcoin/litecoin codebases to compare what I've coded with the real world, but I've some time to spare tomorrow so I'll take a look. I do not promise anything though.
I'll let you know asap.

**Comment by jlopp** [comment]
Yeah I dunno, I've run this tool on 3 different machines and I can't reproduce the problem on the third machine I'm using today. So it may be an even more elusive issue.

**Comment by mycroft** [comment]
Can you try the latest commit? https://github.com/mycroft/generate-genesis/commit/53a3d48e6573f0bec6fb0de65294186b7dbd423c

I think I've identified an issue that would prevent incrementing timestamp in case nonce would be reset when reaching 2^32 (and then would not find any valid hash for a given set of parameters; golang version or system/arch might have some impact of the behavior as well). Therefore I do not think it is a psz size issue at all but more like some stupid issue.

I've also identified and fixed useless sha256 computation and this should improve speed quite a bit. I'm still unhappy with performance so I'll continue investigations.

Hopefully it should help. Unless you're using a very difficult target, it should not take more than a few minutes to find a valid hash when using default difficulty (takes less than 5 min on a i7 12th gen, which is really too slow IMO)

```sh
$ time ./generate-genesis -threads 20 -psz "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks. This is a test!" -nonce 0 -timestamp 1714771870

Ctrl Hash:	0x00000000215add111e09a5afffaac2d30da800723a8fc14404fdff109c86d73b
Target:		0x00000000ffff0000000000000000000000000000000000000000000000000000
Blk Hash:	0x00000000215add111e09a5afffaac2d30da800723a8fc14404fdff109c86d73b
Mkl Hash:	0x2ffa27a19b9934f840cce982e8b207f68e1980cca1eb2afa1864e296fc49554c
Nonce:		3173205127
Timestamp:	1714771870
Pubkey:		04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
Coins:		5000000000
Psz:		'The Times 03/Jan/2009 Chancellor on brink of second bailout for banks. This is a test!'

________________________________________________________
Executed in  254.40 secs    fish           external
   usr time   43.02 mins    0.00 micros   43.02 mins
   sys time    3.97 mins  970.00 micros    3.97 mins
```

**Comment by jlopp** [comment]
Aha, that makes more sense.

Just gave it a shot and seems to be performing quite well!
